### ISSUE TITLE
[Refactor] Change prices text positions and box sizes

### ISSUE THREAD

**Issue by MiguelABFlores** [MiguelABFlores/vet-services-website#34]
When seeing the prices and the format of the text we need to have all with the correct format, titles must be placed in the same horizontal position, size of text and color.
If possible use a carrousel animation for the prices to get it fit in the same box size.

**Comment by johngyek** [comment]
re-sized services boxes with title hover and show their content while hovering each title. 

you can find all that in branch 37-refactor-make-more-compact-every-section

![Image](https://github.com/MiguelABFlores/vet-services-website/assets/29761284/793921f5-03c2-4e32-b8f5-0d05d31d8c8f)

![Image](https://github.com/MiguelABFlores/vet-services-website/assets/29761284/652184ec-c1d1-4407-a690-d44dcd60a691)
